-- =====================================================================
--  EventQ - Database Schema (PostgreSQL)
--  Converted from: newVersion/EventQ_Database_Schema.sql (MySQL 8.0)
--  Target: PostgreSQL 12+
--  Created: 21 September 2026
--
--  Conversion notes (MySQL → PostgreSQL):
--    - AUTO_INCREMENT       → GENERATED BY DEFAULT AS IDENTITY
--    - ENUM(...)            → VARCHAR + named CHECK constraints
--    - JSON                 → JSONB
--    - ON UPDATE CURRENT_TIMESTAMP → updated_at triggers
--    - Backticks            → removed
--    - ENGINE/CHARSET/SET NAMES → removed
--    - FOREIGN_KEY_CHECKS   → removed (PostgreSQL handles FK order via DEFERRABLE)
--    - Inline COMMENT       → moved to column comments via COMMENT ON
--    - DATETIME             → TIMESTAMPTZ (for timestamps with tz context)
--    - Seed statements use ON CONFLICT DO NOTHING for idempotency
--
--  eventq_kv is RETAINED temporarily for one-time legacy migration.
--  After migration, it can be dropped:
--    DROP TABLE IF EXISTS eventq_kv;
-- =====================================================================

-- =====================================================================
-- 0) Legacy compatibility table (one-time migration from old KV backend)
-- =====================================================================
CREATE TABLE IF NOT EXISTS eventq_kv (
    key         VARCHAR(255) PRIMARY KEY,
    value       TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =====================================================================
-- 1) users - Akun pengguna aplikasi (Admin & Public)
-- =====================================================================
CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(50)     NOT NULL,
    password_hash       VARCHAR(255)    NOT NULL,
    full_name           VARCHAR(150)    NOT NULL,
    role                VARCHAR(10)     NOT NULL DEFAULT 'public'
                        CHECK (role IN ('admin','public')),
    is_super_admin      BOOLEAN         NOT NULL DEFAULT FALSE,
    profile_picture_url TEXT            NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_username UNIQUE (username)
);

COMMENT ON TABLE  users IS 'Akun pengguna aplikasi (Admin & Public)';
COMMENT ON COLUMN users.username IS 'Username untuk login, unik di seluruh sistem';
COMMENT ON COLUMN users.password_hash IS 'Kata sandi ter-hash (bcrypt/argon2) - JANGAN pernah simpan plain text';
COMMENT ON COLUMN users.full_name IS 'Nama lengkap pemilik akun';
COMMENT ON COLUMN users.role IS 'Peran akun: admin atau public';
COMMENT ON COLUMN users.is_super_admin IS 'TRUE = Admin pertama di sistem, selalu punya akses penuh';
COMMENT ON COLUMN users.profile_picture_url IS 'URL/path foto profil (file terpisah, bukan base64)';

-- updated_at trigger for users
CREATE OR REPLACE FUNCTION update_users_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_users_updated_at();

-- =====================================================================
-- 2) user_feature_permissions - Hak akses fitur per pengguna
-- =====================================================================
CREATE TABLE IF NOT EXISTS user_feature_permissions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT          NOT NULL,
    feature_key  VARCHAR(50)     NOT NULL,
    is_enabled   BOOLEAN         NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_user_feature UNIQUE (user_id, feature_key),
    CONSTRAINT fk_ufp_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

COMMENT ON TABLE  user_feature_permissions IS 'Hak akses fitur per pengguna (menu Kelola Akses Fitur)';
COMMENT ON COLUMN user_feature_permissions.feature_key IS 'Kode fitur, mis. printSelectedQR, tabScan, kioskMode, dsb';
COMMENT ON COLUMN user_feature_permissions.is_enabled IS 'TRUE = pengguna diizinkan memakai fitur ini';

-- =====================================================================
-- 3) events - Data event/acara
-- =====================================================================
CREATE TABLE IF NOT EXISTS events (
    id                  VARCHAR(20)   NOT NULL PRIMARY KEY,
    name                VARCHAR(150)  NOT NULL,
    event_type          VARCHAR(20)   NOT NULL DEFAULT 'Rumah Sakit'
                        CHECK (event_type IN ('Rumah Sakit','Internal','Lain-lain')),
    event_type_detail   VARCHAR(150)  NULL,
    event_date          TIMESTAMPTZ   NULL,
    logo_url            VARCHAR(500)  NULL,
    needs_seat          BOOLEAN       NOT NULL DEFAULT TRUE,
    seat_label_type     VARCHAR(10)   NOT NULL DEFAULT 'kursi'
                        CHECK (seat_label_type IN ('kursi','meja')),
    needs_hotel         BOOLEAN       NOT NULL DEFAULT FALSE,
    needs_key_signature BOOLEAN       NOT NULL DEFAULT FALSE,
    hidden_columns      JSONB         NULL,
    owner_user_id       BIGINT        NOT NULL,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_events_owner FOREIGN KEY (owner_user_id)
        REFERENCES users (id) ON DELETE RESTRICT
);

COMMENT ON TABLE  events IS 'Data event/acara';
COMMENT ON COLUMN events.id IS 'Kode event, format EVT-XXXXXXXXX';
COMMENT ON COLUMN events.event_type IS 'Jenis acara: Rumah Sakit, Internal, atau Lain-lain';
COMMENT ON COLUMN events.hidden_columns IS 'Array kolom yang disembunyikan, subset dari [rs,jabatan,kursi,kamar,kunci]';
COMMENT ON COLUMN events.owner_user_id IS 'FK -> users.id, pembuat event';

CREATE INDEX IF NOT EXISTS idx_events_owner ON events (owner_user_id);

-- updated_at trigger for events
CREATE OR REPLACE FUNCTION update_events_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_events_updated_at ON events;
CREATE TRIGGER trg_events_updated_at
    BEFORE UPDATE ON events
    FOR EACH ROW
    EXECUTE FUNCTION update_events_updated_at();

-- =====================================================================
-- 4) event_custom_fields - Definisi Nomor Khusus/Unik tambahan per event
-- =====================================================================
CREATE TABLE IF NOT EXISTS event_custom_fields (
    id          VARCHAR(20)  NOT NULL PRIMARY KEY,
    event_id    VARCHAR(20)  NOT NULL,
    label       VARCHAR(100) NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 0,
    CONSTRAINT fk_ecf_event FOREIGN KEY (event_id)
        REFERENCES events (id) ON DELETE CASCADE
);

COMMENT ON TABLE  event_custom_fields IS 'Definisi Nomor Khusus/Unik tambahan per event';
COMMENT ON COLUMN event_custom_fields.id IS 'ID field, dipertahankan dari sistem lama';
COMMENT ON COLUMN event_custom_fields.label IS 'Nama field yang tampil di form & tabel peserta';
COMMENT ON COLUMN event_custom_fields.sort_order IS 'Urutan tampil relatif terhadap field lain';

CREATE INDEX IF NOT EXISTS idx_ecf_event ON event_custom_fields (event_id);

-- =====================================================================
-- 5) event_shared_access - Akses event yang dibagikan ke user Public
-- =====================================================================
CREATE TABLE IF NOT EXISTS event_shared_access (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(20)     NOT NULL,
    user_id     BIGINT          NOT NULL,
    granted_at  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    CONSTRAINT uq_event_user_access UNIQUE (event_id, user_id),
    CONSTRAINT fk_esa_event FOREIGN KEY (event_id)
        REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_esa_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

COMMENT ON TABLE event_shared_access IS 'Daftar user Public yang diberi akses ke sebuah event';
COMMENT ON COLUMN event_shared_access.granted_at IS 'Waktu akses diberikan';

CREATE INDEX IF NOT EXISTS idx_esa_user ON event_shared_access (user_id);

-- =====================================================================
-- 6) guests - Data peserta/tamu (gabungan seluruh event, dibedakan event_id)
-- =====================================================================
CREATE TABLE IF NOT EXISTS guests (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_code           VARCHAR(20)   NOT NULL,
    event_id             VARCHAR(20)   NOT NULL,
    full_name            VARCHAR(150)  NOT NULL,
    institution_origin   VARCHAR(150)  NOT NULL,
    position             VARCHAR(100)  NULL,
    seat_number          VARCHAR(30)   NULL,
    room_number          VARCHAR(30)   NULL,
    key_picked_up        BOOLEAN       NOT NULL DEFAULT FALSE,
    key_picked_up_by     VARCHAR(150)  NULL,
    key_signature_url    VARCHAR(500)  NULL,
    pickup_scanned       BOOLEAN       NOT NULL DEFAULT FALSE,
    pickup_scan_time     TIMESTAMPTZ   NULL,
    attendance_scanned   BOOLEAN       NOT NULL DEFAULT FALSE,
    attendance_scan_time TIMESTAMPTZ   NULL,
    created_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_guest_code_per_event UNIQUE (event_id, guest_code),
    CONSTRAINT fk_guests_event FOREIGN KEY (event_id)
        REFERENCES events (id) ON DELETE CASCADE
);

COMMENT ON TABLE  guests IS 'Data peserta/tamu per event';
COMMENT ON COLUMN guests.guest_code IS 'Kode tercetak di kartu QR, format QIS-/INT-/LNL-XXXXXXXXX';
COMMENT ON COLUMN guests.institution_origin IS 'Asal RS/Instansi';
COMMENT ON COLUMN guests.key_picked_up IS 'TRUE = kunci kamar sudah diambil';
COMMENT ON COLUMN guests.key_picked_up_by IS 'Nama pengambil kunci (bisa diwakilkan)';
COMMENT ON COLUMN guests.key_signature_url IS 'URL/path bukti tanda tangan';
COMMENT ON COLUMN guests.pickup_scanned IS 'TRUE = QR Kiosk Pengambilan sudah pernah dipindai';
COMMENT ON COLUMN guests.attendance_scanned IS 'Status kehadiran peserta';

CREATE INDEX IF NOT EXISTS idx_guests_event ON guests (event_id);
CREATE INDEX IF NOT EXISTS idx_guests_attendance ON guests (event_id, attendance_scanned);

-- updated_at trigger for guests
CREATE OR REPLACE FUNCTION update_guests_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_guests_updated_at ON guests;
CREATE TRIGGER trg_guests_updated_at
    BEFORE UPDATE ON guests
    FOR EACH ROW
    EXECUTE FUNCTION update_guests_updated_at();

-- =====================================================================
-- 7) guest_custom_field_values - Nilai Nomor Khusus/Unik tiap peserta
-- =====================================================================
CREATE TABLE IF NOT EXISTS guest_custom_field_values (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id               BIGINT          NOT NULL,
    event_custom_field_id  VARCHAR(20)     NOT NULL,
    value                  VARCHAR(100)    NULL,
    CONSTRAINT uq_guest_field UNIQUE (guest_id, event_custom_field_id),
    CONSTRAINT fk_gcfv_guest FOREIGN KEY (guest_id)
        REFERENCES guests (id) ON DELETE CASCADE,
    CONSTRAINT fk_gcfv_field FOREIGN KEY (event_custom_field_id)
        REFERENCES event_custom_fields (id) ON DELETE CASCADE
);

COMMENT ON TABLE guest_custom_field_values IS 'Nilai Nomor Khusus/Unik tiap peserta';

CREATE INDEX IF NOT EXISTS idx_gcfv_field ON guest_custom_field_values (event_custom_field_id);

-- =====================================================================
-- 8) custom_qr_codes - QR Code kustom (tool Custom QR Code Generator)
-- =====================================================================
CREATE TABLE IF NOT EXISTS custom_qr_codes (
    id          VARCHAR(20)  NOT NULL PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    content     TEXT         NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE custom_qr_codes IS 'QR Code kustom dari tool Custom QR Code Generator';

-- =====================================================================
-- 9) custom_barcodes - Barcode kustom (tool Custom Barcode Generator)
-- =====================================================================
CREATE TABLE IF NOT EXISTS custom_barcodes (
    id          VARCHAR(20)  NOT NULL PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    content     TEXT         NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE custom_barcodes IS 'Barcode kustom dari tool Custom Barcode Generator';

-- =====================================================================
-- 10) login_bg_images - Foto latar belakang halaman login (slideshow)
-- =====================================================================
CREATE TABLE IF NOT EXISTS login_bg_images (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url   VARCHAR(500) NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 0
);

COMMENT ON TABLE login_bg_images IS 'Foto latar belakang halaman login (mandiri, satu set untuk seluruh sistem)';

-- =====================================================================
-- 11) app_settings - Pengaturan aplikasi global (key-value)
-- =====================================================================
CREATE TABLE IF NOT EXISTS app_settings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key   VARCHAR(60) NOT NULL,
    setting_value TEXT        NULL,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_setting_key UNIQUE (setting_key)
);

COMMENT ON TABLE app_settings IS 'Pengaturan aplikasi global (satu baris per pengaturan, single-tenant)';

-- updated_at trigger for app_settings
CREATE OR REPLACE FUNCTION update_app_settings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_app_settings_updated_at ON app_settings;
CREATE TRIGGER trg_app_settings_updated_at
    BEFORE UPDATE ON app_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_app_settings_updated_at();


-- =====================================================================
--  DATA AWAL (SEED) - OPSIONAL, IDEMPOTENT
--  ON CONFLICT DO NOTHING supaya bisa dijalankan berulang kali tanpa error.
-- =====================================================================
INSERT INTO app_settings (setting_key, setting_value) VALUES
    ('app_logo',                    NULL),
    ('auth_caption',                NULL),
    ('dark_mode',                   'false'),
    ('kiosk_audio_enabled',         'true'),
    ('kiosk_exit_pin',              NULL),
    ('kiosk_pickup_signature',      'false'),
    ('kiosk_reset_duration',        '4'),
    ('kiosk_tts_enabled',           'true'),
    ('kiosk_tts_lang',              'id-ID'),
    ('library_filter_category',     'all'),
    ('library_sort_mode',           'newest'),
    ('library_view_mode',           'grid'),
    ('print_qr_fields',             NULL),
    ('print_custom_qr_fields',      NULL),
    ('print_custom_barcode_fields', NULL),
    ('app_lang',                    'id')
ON CONFLICT (setting_key) DO NOTHING;

-- =====================================================================
--  Akun Super Admin awal - OPSIONAL, WAJIB DIGANTI setelah instalasi.
--  Password: "ubah_password_ini" (disimpan plaintext — selaras dengan
--  frontend auth.js yang melakukan perbandingan langsung).
--  Setelah yakin migrasi/sistem berjalan, ganti password lewat UI dan
--  hash backend via passlib/bcrypt (lihat README §3 Catatan Keamanan).
-- =====================================================================
INSERT INTO users (username, password_hash, full_name, role, is_super_admin)
VALUES (
    'superadmin',
    'ubah_password_ini',
    'Super Admin',
    'admin',
    TRUE
) ON CONFLICT (username) DO NOTHING;
